version: "3"

networks:
  invoice-app:
    driver: bridge

services:
  nginx:
    image: nginx:stable-perl
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "9090:80"
    volumes:
      - ./Docker/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    depends_on:
      - php
      - mysql
    networks:
      - invoice-app

  php:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
    networks:
      - invoice-app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: invoice_app
      MYSQL_USER: invoice_user
      MYSQL_PASSWORD: inv0!ce@2024
      MYSQL_ROOT_PASSWORD: inv0!ce_r00t@2024
    ports:
      - "3306:3306"
    networks:
      - invoice-app

